### ISSUE TITLE
Enable language_chooser get error

### ISSUE THREAD

**Issue by yswtrue** [farridav/django-jazzmin#260]
```
django==3.1.7
django-jazzmin==2.4.4
```

```
Traceback (most recent call last):
  File "/home/yswtrue/Code/seatower_erp/.venv/lib/python3.9/site-packages/django/core/handlers/wsgi.py", line 133, in __call__
    response = self.get_response(request)
  File "/home/yswtrue/Code/seatower_erp/.venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 130, in get_response
    response = self._middleware_chain(request)
  File "/home/yswtrue/Code/seatower_erp/.venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 49, in inner
    response = response_for_exception(request, exc)
  File "/home/yswtrue/Code/seatower_erp/.venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 103, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/home/yswtrue/Code/seatower_erp/.venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 138, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/home/yswtrue/Code/seatower_erp/.venv/lib/python3.9/site-packages/django_extensions/management/technical_response.py", line 40, in null_technical_500_response
    raise exc_value.with_traceback(tb)
  File "/home/yswtrue/Code/seatower_erp/.venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/yswtrue/Code/seatower_erp/.venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 204, in _get_response
    response = response.render()
  File "/home/yswtrue/Code/seatower_erp/.venv/lib/python3.9/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/home/yswtrue/Code/seatower_erp/.venv/lib/python3.9/site-packages/django/template/response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "/home/yswtrue/Code/seatower_erp/.venv/lib/python3.9/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/yswtrue/Code/seatower_erp/.venv/lib/python3.9/site-packages/django/template/base.py", line 170, in render
    return self._render(context)
  File "/home/yswtrue/Code/seatower_erp/.venv/lib/python3.9/site-packages/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/yswtrue/Code/seatower_erp/.venv/lib/python3.9/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/home/yswtrue/Code/seatower_erp/.venv/lib/python3.9/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/yswtrue/Code/seatower_erp/.venv/lib/python3.9/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/home/yswtrue/Code/seatower_erp/.venv/lib/python3.9/site-packages/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/yswtrue/Code/seatower_erp/.venv/lib/python3.9/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/home/yswtrue/Code/seatower_erp/.venv/lib/python3.9/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/yswtrue/Code/seatower_erp/.venv/lib/python3.9/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/home/yswtrue/Code/seatower_erp/.venv/lib/python3.9/site-packages/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/yswtrue/Code/seatower_erp/.venv/lib/python3.9/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/home/yswtrue/Code/seatower_erp/.venv/lib/python3.9/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/yswtrue/Code/seatower_erp/.venv/lib/python3.9/site-packages/django/template/defaulttags.py", line 312, in render
    return nodelist.render(context)
  File "/home/yswtrue/Code/seatower_erp/.venv/lib/python3.9/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/home/yswtrue/Code/seatower_erp/.venv/lib/python3.9/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/yswtrue/Code/seatower_erp/.venv/lib/python3.9/site-packages/django/template/defaulttags.py", line 312, in render
    return nodelist.render(context)
  File "/home/yswtrue/Code/seatower_erp/.venv/lib/python3.9/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/home/yswtrue/Code/seatower_erp/.venv/lib/python3.9/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/yswtrue/Code/seatower_erp/.venv/lib/python3.9/site-packages/django/template/defaulttags.py", line 446, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/yswtrue/Code/seatower_erp/.venv/lib/python3.9/site-packages/django/urls/base.py", line 87, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "/home/yswtrue/Code/seatower_erp/.venv/lib/python3.9/site-packages/django/urls/resolvers.py", line 685, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'set_language' not found. 'set_language' is not a valid view function or pattern name.
```

**Comment by farridav** [comment]
Are you sure you have the internationalisation setup in Django ? Check out or demo app, especially the URLs.py you may be missing an include..

**Comment by yswtrue** [comment]
I add i18n config for urls, and it works now. Thank you.
[](https://github.com/farridav/django-jazzmin/blob/ec7971c9ba28e572b1fce7679ab028cae6b54b25/tests/test_app/library/urls.py#L28-L31)
